# Create Artifact Registry repository
resource "google_artifact_registry_repository" "todoapp" {
    location      = var.region
    repository_id = var.repo_name
    description   = "Repository for the best todo app ever created in the history of the world and the universe and everything else that exists (generated by copilot :D)"
    format        = "DOCKER"

    mode          = "STANDARD_REPOSITORY"
}

# Build docker images
resource "docker_image" "todoapp" {
    for_each = var.todoapp_services

    name = "${local.gcp_artifact_registry_repository}/${each.key}"

    build {
        context    = "${path.cwd}/containers"

        build_args = {
            DB_NAMESPACE   = var.todoapp_namespace
            SERVICE_NAME   = each.key
            PORT           = each.value.container-port
        }
    }

    keep_locally = false
}

resource "docker_registry_image" "todoapp" {
    depends_on = [
        docker_image.todoapp,
        google_artifact_registry_repository.todoapp
    ]

    for_each = docker_image.todoapp

    name = each.value.name

    keep_remotely = false
}
